### ISSUE TITLE
Section 3.2 Editor note: Reconnaissance Phase (Is there a need for a minimum required number of RTT samples to confirm a path?)

### ISSUE THREAD

**Issue by joergdeutschmann-i7** [tsvwg/careful-resume#22]
A few thoughts on what could happen considering IW=10 packets
- One ACK is received for every packet (ACK ratio = 1:1), this would result in 10 RTT measurements
- One ACK is received for every other packet (ACK ratio = 1:2) as recommended in RFC9000 ("A receiver SHOULD send an ACK frame after receiving at least two ack-eliciting packets"), this would result in 5 RTT measurements
- One ACK is received for the whole IW (ACK ratio = 1:10 but unlikely?), this would result in only one RTT measurement

**Comment by gorryfair** [comment]
All true - I'm not sure the draft can add much clarity around this topic across the range of practical paths, patterns of transmission and receiver ACK policy : I wonder whether we should resolve this with no additional text?

**Comment by joergdeutschmann-i7** [comment]
Regarding my example: If the cwnd is given in bytes and the packets are very small, it could be even more RTT samples.

Not sure if something like this could be helpful:
`Reconnaissance Phase (RTT samples): The number of RTT samples available in this phase varies depending on the implementation.`
and maybe
`..., at least one RTT sample MUST be available.`
But both is kind of obvious.

So yes, probably best to resolve this without additional text.

**Comment by gorryfair** [comment]
I agree with the peposal to close with a minor edit.

BTW: "Regarding my example: If the cwnd is given in bytes and the packets are very small, it could be even more RTT samples."
- Is that so?  TCP would have ACK'ed every other MSS (or ACK_Del).

**Comment by joergdeutschmann-i7** [comment]
> Is that so? TCP would have ACK'ed every other MSS (or ACK_Del).

Yes, RFC9293 says `An ACK SHOULD be generated for at least every second full-sized segment or 2*RMSS bytes of new data`
Accordingly, RFC9000 says `A receiver SHOULD send an ACK frame after receiving at least two ack-eliciting packets.`

My (rather hypothetical) thought was more "how many RTT measurements could I get out if the IW"

**Comment by TheEnbyperor** [comment]
To chime in with my experience from testing this on real-world connections;

In 1-RTT connections this isn't an issue, there's more than enough back and forth chatter (initial packets, crypto frames, HTTP/3 settings exchange, etc) before the app-limited stage is entered to get a good idea of the RTT.

In 0-RTT not much of this really happens, since the whole HTTP/3 setup (or whatever other protocol you're using) can be sent in one big chunk. I think therefore the spec should include a SHOULD (BCP14) on how many samples should be taken before proceeding with CR.

**Comment by gorryfair** [comment]
It still seems akwards to have a "SHOULD" for how many samples, to me, it seems the usefulness of a set of RTT samples rather depends on the independence of their measurements. At the moment, I don't know how to express that as a requirement that is meaningful, I'd like to be able to tell how representative that RTT samples will be of the path when I use it, is that something we can know?

**Comment by TheEnbyperor** [comment]
Off the top of my head I think the best measure for independence of RTT samples is the times between when the data that is being acked was sent out.

So, a run of RTT samples based on paced out data is more representative than RTT samples based on a load of data sent in very quick succession.

**Comment by gorryfair** [comment]
I's agree pacing the data is likely to find a better minRTT (which is what is needed in this case). Although pacing across an RTT (or a fraction of an RTT) also costs time, and whether that is great, or not, might depend on the usage. I expect the form of pacing of IW is an implementation/policy decision.

**Comment by TheEnbyperor** [comment]
If I were more of a statistician I'd come up with some function that relates variance between RTT samples and time between data being sent, and use that. This is a poorly disguised invitation for someone who is better as statistics to try.

**Comment by joergdeutschmann-i7** [comment]
But please let's not use complex stochastic calculations in the draft 😅

**Comment by gorryfair** [comment]
Let's look at the text about how minRTT is calculated from the ACKs received in the Recon. Phase to see if we can find a way to close this.

**Comment by gorryfair** [comment]
The current text says:
During this (the recon)  phase, a sender MUST record the minimum RTT for the current connection as the current_rtt.

And then:
Reconnaissance Phase (Path confirmed): When a sender has confirmed the RTT and also has received an acknowledgement for the initial data without reported congestion, it MAY then enter the Unvalidated Phase. This transition occurs when a sender has more data than permitted by the current CWND.

... To me this clearly allows a sender to combine multiple RTT samples when calculating the Min RTT, and since the IW is typically 10 packets, and it is common to receive ACKs for every second packet, this would suggest this is often 5 RTT measurements. 

I suspect this is sufficient for most cases.

**Comment by joergdeutschmann-i7** [comment]
Yes. The text in the current draft is clear and appropriate.

**Comment by csujedihy** [comment]
> > Is that so? TCP would have ACK'ed every other MSS (or ACK_Del).
> 
> Yes, RFC9293 says `An ACK SHOULD be generated for at least every second full-sized segment or 2*RMSS bytes of new data` Accordingly, RFC9000 says `A receiver SHOULD send an ACK frame after receiving at least two ack-eliciting packets.`
> 
> My (rather hypothetical) thought was more "how many RTT measurements could I get out if the IW"

I came from #112 and just saw the discussion. Just wanted to add one point here: on Windows, with RSC HW/SW offload and our TCPIP batch optimization (some would refer to it as stretch ACKs), it's very likely that you get just one ACK for IW. It's possible to get one or two ACKs for even 100+ MSS worth of data packets.
